### ISSUE TITLE
BNK 编码疑似存在 bug

### ISSUE THREAD

**Issue by MeteorFlower** [twinstar6980/Twinning#30]
如题。将 GLOBAL_DATA 解码并原样编码，出现了钢琴的技能音乐断断续续的 bug。发现编码的生成结果与原始文件并不完全相同。
此外，用太极解码并编码似乎并不会出现这个问题。

**Comment by DRPLANT666** [comment]
没人？

**Comment by Haruma-VN** [comment]
Maybe provide the bnk and the soundbank directory sample so the author could check?

**Comment by twinstar6980** [comment]
这可能是由于工具错误地将一些值判定为默认值，从而未将其编码进 bnk 中，导致音乐出现问题。但目前没有时间与精力去排查 bnk 相关的 BUG ，它的文件结构过分复杂。
