### ISSUE TITLE
Assistant Animation Viewer issue

### ISSUE THREAD

**Issue by Haruma-VN** [twinstar6980/Twinning#33]
When I load a pam json with the assistant, the assistant throw an exception.

![Screenshot_2024-10-01-17-49-11-955_com.twinstar.twinning.assistant.jpg](https://github.com/user-attachments/assets/1e21f7ff-9480-4fc4-9d39-abc5a28aec60)

**Comment by twinstar6980** [comment]
Note: animationviewer is a WIP feature, currently it can only play pam very simply, but cannot control or select sprites.

1. Select the pam.json file in the file picker.
2. Make sure there is no trailing comma in pam.json.
3. Make sure all image files required by pam are in the same directory.

Example:
[aloe.zip](https://github.com/user-attachments/files/17204021/aloe.zip)

**Comment by twinstar6980** [comment]
Assistant's AnimationViewer now works basically.
